baseURL: https://herminiosabino.github.io/
theme: hugo-apero
languageCode: en
title: Hermínio Sabino
author: Hermínio Sabino
copyright: ''
googleAnalytics: ''
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 5
preserveTaxonomyNames: yes
publishDir: 'docs/'
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  custom_theme: ''
  customheadingFontFamily: Fraunces
  customtextFontFamily: Commissioner
  description: A modern, beautiful, and easily configurable blog theme for Hugo.
  favicon: /img/favicon.ico
  headingFontFamily: sans-serif
  logo: /img/blogophonic-mark-dark.png
  mainSections:
    - blog
    - project
    - talk
  navallcaps: yes
  orgLocal: Anywhere
  orgName: RStudio
  sharing_image: /img/papillons.jpg
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/HerminioSabino
    - icon: facebook-square
      icon_pack: fab
      url: https://www.facebook.com/ herminio.sabino.7
    - icon: instagram
      icon_pack: fab
      url: https://www.instagram.com/herminiosabino/
    - icon: twitter
      icon_pack: fab
      url: https://twitter.com/Herminio_Sabino
    - icon: linkedin
      icon_pack: fab
      url: https://www.linkedin.com/in/herm%C3%ADnio-sabino-0b087381/
    - icon: youtube
      icon_pack: fab
      url: https://www.youtube.com/c/hsgeotec
    - icon: telegram
      icon_pack: fab
      url: https://t.me/HerminioSabino
    - icon: orcid
      icon_pack: ai
      url: https://orcid.org/0000-0001-9056-9839
    - icon: lattes
      icon_pack: ai
      url: http://lattes.cnpq.br/0780797316163220
    - icon: google-scholar
      icon_pack: ai
      url: https://scholar.google.com.br/citations?hl=pt-BR&user=sTzjRtUAAAAJ
    - icon: twitch
      icon_pack: fab
      url: https://www.twitch.tv/herminiosabino
   
  socialInFooter: yes
  socialInHeader: no
  textFontFamily: sans-serif
  theme: sky
  twitter: apreshill
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: apreshill/apero
    theme: boxy-light
    use_utterances: yes
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
    
    - name: Contributors
      title: Contributors
      url: /contributors/
      weight: 3
  header:
    - name: Sobre
      title: About Blogophonic
      url: /about/
      weight: 1
    - name: Blog
      title: Blog
      url: /blog/
      weight: 2
    - name: Projetos
      title: Project Portfolio
      url: /project/
      weight: 3
    
   
privacy:
  disqus:
    disable: no
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: no
    simple: yes
  twitter:
    disable: no
    enableDNT: yes
    simple: no
  vimeo:
    disable: no
    enableDNT: yes
    simple: yes
  youtube:
    disable: no
    privacyEnhanced: yes
